spring.application.name=Lost_Found_Backend

spring.datasource.url=jdbc:mysql://hopper.proxy.rlwy.net:26618/Lost_Found_Db
spring.datasource.username=root
spring.datasource.password=OILwXwCZJkjyPyFrjUaVOIdzWbTlIROb

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
